django/config/urls.py
from django.contrib import admin
from django.urls import path, include

import core.urls
import user.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include(user.urls, namespace='user')),
    path('', include(core.urls, namespace='core'))
]

django/core/urls.py
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('movies', views.MovieList.as_view(), name='MovieList'),
    path('movie/<int:pk>', views.MovieDetail.as_view(), name='MovieDetail'),
    path('person/<int:pk>', views.PersonDetail.as_view(), name="PersonDetail")
]

django/user/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from user import views

app_name = 'user'

urlpatterns = [
    path('register', views.RegisterView.as_view(), name='register'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout')
]

django/core/models.py
from django.db import models


class MovieManager(models.Manager):
    def all_with_related_person(self):
        qs = self.get_queryset()
        qs = qs.select_related('director')
        qs = qs.prefetch_related('writer', 'actors')
        return qs


class Movie(models.Model):
    NOT_RATED = 0
    RATED_G = 1
    RATED_PG = 2
    RATED_R = 3
    RATINGS = (
        (NOT_RATED, 'NR - Not Rated'),
        (RATED_G, 'G - General Audiences'),
        (RATED_PG, 'Parental Guidance '
                   'Suggested'),
        (RATED_R, 'R - Restricted'),
    )
    title = models.CharField(max_length=140)
    plot = models.TextField()
    year = models.PositiveIntegerField()
    rating = models.IntegerField(choices=RATINGS, default=NOT_RATED)
    runtime = models.PositiveIntegerField()
    website = models.URLField(blank=True)
    director = models.ForeignKey(to='Person', on_delete=models.SET_NULL,
                                 related_name='directed', null=True, blank=True)
    writer = models.ManyToManyField(to='Person', related_name='writing_credits',
                                    blank=True)
    actors = models.ManyToManyField(to='Person', through='Role', related_name='acting_credits',
                                    blank=True)

    objects = MovieManager()

    class Meta:
        ordering = ('-year', 'title')

    def __str__(self):
        return '{} ({})'.format(self.title, self.year)


class PersonManager(models.Manager):
    def all_with_prefetch_movies(self):
        qs = self.get_queryset()
        return qs.prefetch_related('directed',
                                   'writing_credits',
                                   'role_set')


class Person(models.Model):
    first_name = models.CharField(max_length=140)
    last_name = models.CharField(max_length=140)
    born = models.DateField()
    died = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ('last_name', 'first_name')

    objects = PersonManager()

    def __str__(self):
        if self.died:
            return '{}, {},({} -{})'.format(self.first_name, self.last_name, self.born, self.died)
        else:
            return '{}, {},({})'.format(self.first_name, self.last_name, self.born)


class Role(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.DO_NOTHING)
    person = models.ForeignKey(Person, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=140)

    class Meta:
        unique_together = ('movie', 'person', 'name')

    def __str__(self):
        return "{} {} {}".format(self.movie_id, self.person_id, self.name)

django/user/models.py
from django.db import models

# Create your models here.

django/core/views.py
from django.views.generic import ListView, DetailView

from core.models import Movie, Person


class MovieList(ListView):
    model = Movie
    paginate_by = 10


class MovieDetail(DetailView):
    queryset = (Movie.objects.all_with_related_person())


class PersonDetail(DetailView):
    queryset = Person.objects.all_with_prefetch_movies()
# Create your views here.

django/user/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView

class RegisterView(CreateView):
    template_name = 'user/register.html'
    form_class = UserCreationForm
    success_url =  reverse_lazy(
        'core:MovieList'
    )

django/core/templates/core/movie_detail.html
{% extends 'base.html' %}

{% block title%}
    {{object.title}} - {{block.super}}
{% endblock%}

{% block main %}
<h1>{{object}}</h1>
<p class ="lead">

    {{object.plot}}
</p>
{% endblock %}

{% block sidebar%}
<div>
    This movie is rated :
    <span class="badge badge-primary">
        {{ object.get_rating_display }}
    </span>
</div>

{% endblock %}

django/core/templates/core/movie_list.html
{% extends 'base.html' %}

{% block title%}
    All Movie - {{block.super}}
{% endblock%}


{% block main %}
<ul>
    {% for  movie in object_list  %}
    <li>
        <a href="{% url 'core:MovieDetail' pk=movie.id %}">
            {{movie}}
        </a>
    </li>
    {% endfor %}
</ul>

{% if is_paginated %}
<nav>
    <ul class ="pagination">
        <li class="page-item">
            <a href="{% url 'core:MovieList'%}?page=1" class="page-link">
                First
            </a>
        </li>
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a href="{% url 'core:MovieList'%}?page={{ page_obj.previous_page_number }}" class="page-link">
                {{ page_obj.previous_page_number }}
            </a>
        </li>
        {% endif %}
        <li class="page-item active">
            <a href="{% url 'core:MovieList'%}?page={{ page_obj.number }}" class="page-link">
                {{ page_obj.number }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a href="{% url 'core:MovieList'%}?page={{ page_obj.next_page_number }}" class="page-link">
                {{ page_obj.next_page_number }}
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a href="{% url 'core:MovieList'%}?page=last" class="page-link">
                Last
            </a>
        </li>
    </ul>
</nav>
{% endif %}
{% endblock %}

django/core/templates/core/person_detail.html
{% extends 'base.html' %}

{% block title%}
    {{object.first_name}}
    {{object.last_name}}
{% endblock%}

{% block main %}
<h1>{{object}}</h1>
<h2>Actor</h2>

<ul>
    {% for  role in object.role_set.all  %}
    <li>
        <a href="{% url 'core:MovieDetail' pk=role.movie.id %}">
            {{role.movie}}
        </a>:{{role.name}}
    </li>
    {% endfor %}
</ul>

<h2>Writer</h2>
<ul>
    {% for  movie in object.writing_credit.all  %}
    <li>
        <a href="{% url 'core:MovieDetail' pk=movie.id %}">
            {{movie}}
        </a>
    </li>
    {% endfor %}
</ul>

<h2>Director</h2>
<ul>
    {% for  movie in object.directed.all  %}
    <li>
        <a href="{% url 'core:MovieDetail' pk=movie.movie.id %}">
            {{movie}}
        </a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

django/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
<title> {% block title%}MYMDB{% endblock %}</title>
</head>
<style>
.mymdb-masthead{
    background-color: #EEEEEE;
     margin-bottom: 1em;
    }
</style>
<body>
<div class="mymdb-masthead">
    <div class="container">
        <nav class="nav">
            <div class="navbar-brand">
                MYMDB
            </div>
            <a class="nav-link" href="{% url 'core:MovieList' %}">
                Movies
            </a>
        </nav>

    </div>
</div>
<div class = "container">
    <div class ="row">
        <div class="col-md-8 mymdb-main">
            {% block main%}{% endblock %}
        </div>
        <div class="col-md-3 offset-sm-1 mymdb-sidebar">
            {% block sidebar%}{% endblock %}
        </div>
    </div>
</div>
</body>
</html>

django/user/templates/user/register.html
{% extends 'base.html' %}


{% block main %}
<h1>Register for MYmdb</h1>
<form method="post">
    {{form.as_p}}
    {% csrf_token %}

    <button type="submit" class="btn btn-primary"> Register</button>
</form>
{% endblock %}